services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gestaodeincidentes
    ports:
      - "8081:8080"
    env_file: .env

    environment:
      DEPLOY_URL: ${DEPLOY_URL}
      DEPLOY_USERNAME: ${DEPLOY_USER}
      DEPLOY_PASSWORD: ${DEPLOY_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev