services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gestaodeincidentes
    ports:
      - "8081:8080"
    env_file: .env

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://switchyard.proxy.rlwy.net:47484/railway
      SPRING_DATASOURCE_USERNAME: ${DEPLOY_USER}
      SPRING_DATASOURCE_PASSWORD: ${DEPLOY_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev